version: "2"
services:
  nginx:
    image: nginx:alpine
    volumes: 
      - "./build:/public:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "5000:80"

  landslide:
    image: grihabor/landslide:latest
    build:
      context: landslide
      dockerfile: Dockerfile
    volumes:
      - "./src:/src"
      - "./build:/build"
          
